// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type lockFutexInfo struct {
	LockAddress uint64
	Op          uint32
	Pad         uint32
}

type lockLockKey struct {
	Tgid        uint32
	Tid         uint32
	LockAddress uint64
	Stackid     int32
	FutexOp     uint32
}

type lockLockStat struct {
	OffcpuNs    uint64
	OffcpuCount uint64
	LastWaker   uint32
	Pad         uint32
	Comm        [16]int8
	Slots       [48]uint64
}

type lockOffcpuInfo struct {
	Ts           uint64
	LockAddress  uint64
	TaskIdentity uint64
	Tgid         uint32
	Tid          uint32
	Stackid      int32
	FutexOp      uint32
	LastWaker    uint32
	Pad          uint32
}

// loadLock returns the embedded CollectionSpec for lock.
func loadLock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lock: %w", err)
	}

	return spec, err
}

// loadLockObjects loads lock and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lockObjects
//	*lockPrograms
//	*lockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLockObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lockSpecs struct {
	lockProgramSpecs
	lockMapSpecs
}

// lockSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lockProgramSpecs struct {
	HandleFutexEnter *ebpf.ProgramSpec `ebpf:"handle_futex_enter"`
	HandleFutexExit  *ebpf.ProgramSpec `ebpf:"handle_futex_exit"`
	HandleSwitch     *ebpf.ProgramSpec `ebpf:"handle_switch"`
	HandleWakeup     *ebpf.ProgramSpec `ebpf:"handle_wakeup"`
	HandleWakeupNew  *ebpf.ProgramSpec `ebpf:"handle_wakeup_new"`
}

// lockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lockMapSpecs struct {
	FutexActive   *ebpf.MapSpec `ebpf:"futex_active"`
	Health        *ebpf.MapSpec `ebpf:"health"`
	LockStatZero  *ebpf.MapSpec `ebpf:"lock_stat_zero"`
	LockStats     *ebpf.MapSpec `ebpf:"lock_stats"`
	ObservedTgids *ebpf.MapSpec `ebpf:"observed_tgids"`
	OffcpuStart   *ebpf.MapSpec `ebpf:"offcpu_start"`
	Stackmap      *ebpf.MapSpec `ebpf:"stackmap"`
	TargetPid     *ebpf.MapSpec `ebpf:"target_pid"`
	TargetTgids   *ebpf.MapSpec `ebpf:"target_tgids"`
}

// lockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLockObjects or ebpf.CollectionSpec.LoadAndAssign.
type lockObjects struct {
	lockPrograms
	lockMaps
}

func (o *lockObjects) Close() error {
	return _LockClose(
		&o.lockPrograms,
		&o.lockMaps,
	)
}

// lockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLockObjects or ebpf.CollectionSpec.LoadAndAssign.
type lockMaps struct {
	FutexActive   *ebpf.Map `ebpf:"futex_active"`
	Health        *ebpf.Map `ebpf:"health"`
	LockStatZero  *ebpf.Map `ebpf:"lock_stat_zero"`
	LockStats     *ebpf.Map `ebpf:"lock_stats"`
	ObservedTgids *ebpf.Map `ebpf:"observed_tgids"`
	OffcpuStart   *ebpf.Map `ebpf:"offcpu_start"`
	Stackmap      *ebpf.Map `ebpf:"stackmap"`
	TargetPid     *ebpf.Map `ebpf:"target_pid"`
	TargetTgids   *ebpf.Map `ebpf:"target_tgids"`
}

func (m *lockMaps) Close() error {
	return _LockClose(
		m.FutexActive,
		m.Health,
		m.LockStatZero,
		m.LockStats,
		m.ObservedTgids,
		m.OffcpuStart,
		m.Stackmap,
		m.TargetPid,
		m.TargetTgids,
	)
}

// lockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLockObjects or ebpf.CollectionSpec.LoadAndAssign.
type lockPrograms struct {
	HandleFutexEnter *ebpf.Program `ebpf:"handle_futex_enter"`
	HandleFutexExit  *ebpf.Program `ebpf:"handle_futex_exit"`
	HandleSwitch     *ebpf.Program `ebpf:"handle_switch"`
	HandleWakeup     *ebpf.Program `ebpf:"handle_wakeup"`
	HandleWakeupNew  *ebpf.Program `ebpf:"handle_wakeup_new"`
}

func (p *lockPrograms) Close() error {
	return _LockClose(
		p.HandleFutexEnter,
		p.HandleFutexExit,
		p.HandleSwitch,
		p.HandleWakeup,
		p.HandleWakeupNew,
	)
}

func _LockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lock_bpfel.o
var _LockBytes []byte
